### ISSUE TITLE
Pratica 2_bizagi

### ISSUE THREAD

**Issue by ka194** [SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-ka194#1]
[practica2_bizagi.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-ka194/files/12825952/practica2_bizagi.pdf)

**Comment by YaelStO** [comment]
18/20 Buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
